baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  body_classes = "avenir bg-near-white"
  text_color = "mid-gray"
  background_color_class = "bg-black"
  post_content_classes = "serif"
  show_reading_time = true
